### ISSUE TITLE
the trained models

### ISSUE THREAD

**Issue by haile-vnu** [MFaceTech/InstantID#1]
Hi, 

It is great when you can reproduce the results.
Do you have a plan to release your trained models, so we can run both of the origin models from InstantX and your models.

Thank you very much!

**Comment by chenxinhua** [comment]
I'm very sorry, the model is trained on private datasets, so it cannot be made public.

**Comment by chenxinhua** [comment]
> Hi,
> 
> It is great when you can reproduce the results. Do you have a plan to release your trained models, so we can run both of the origin models from InstantX and your models.
> 
> Thank you very much!


I'm very sorry, the model is trained on private datasets, so it cannot be made public.

**Comment by haile-vnu** [comment]
It is clear. Thank you for your code sharing!
