### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by LeonNerd** [MFaceTech/InstantID#11]
I used 40,000 datasets for fine-tuning and trained for 8 epochs. I found that the face ID was not maintained.
Is this because there are not enough epochs or there is an error in the data?

![image](https://github.com/user-attachments/assets/74459c7e-80b3-4a4b-9ca7-d9ca0f4d7b04)
![image](https://github.com/user-attachments/assets/0346fe65-db1b-4089-bbfb-ad6f74f58b36)

**Comment by chenxinhua** [comment]
Whether you choose to fine-tune or train from scratch, 40,000 images with 8 epochs should yield a significant effect on ID preservation, but you must first ensure that the input image size is 1024x1024.

**Comment by chenxinhua** [comment]
Whether you choose to fine-tune or train from scratch, 40,000 images with 8 epochs should result in good ID preservation effects, but you must  ensure that the image size to the model is 1024*1024.

**Comment by LeonNerd** [comment]
> Whether you choose to fine-tune or train from scratch, 40,000 images with 8 epochs should result in good ID preservation effects, but you must ensure that the image size to the model is 1024*1024.
Thank you for your attention. I am also wondering why this problem occurs, because my images are generated, so the size is 1024. Now I suspect that there is an error in my training data processing. I need to check.
Below is the training configuration and sample data：
![image](https://github.com/user-attachments/assets/a54c093d-32fc-4beb-afb1-45ee07b41c86)

**Comment by LeonNerd** [comment]
During the data processing, is there anything that needs to be modified in get_face_info.py? For example, max_side in the resize_img function?
