### ISSUE TITLE
is the model finetuned base on the pretrained instantid model?

### ISSUE THREAD

**Issue by min-star** [MFaceTech/InstantID#5]

**Comment by min-star** [comment]
I found the code with ipadapter_model_pretrain_path

 ` ip_adapter = InstantIDAdapter(unet, controlnet, feature_proj_model, adapter_modules, args.pretrained_ip_adapter_path)`

**Comment by chenxinhua** [comment]
yes， you can finetune on  the pretrained instantid model or train from scratch.

**Comment by min-star** [comment]
Thanks,I want to konw whether you train the model from scratch or not,how much dataset and the spend time.I already konw you trained with a a100 80G machine.
